### ISSUE TITLE
initial CRUD support for beats

### ISSUE THREAD

**Issue by victorkane** [awebfactory/kalliope-prototype-01#2]
First iteration in order for the app to support the creation, listing, viewing, updating and deletion of beats.

**Comment by FacuuLopez** [comment]
- [ ] set up next.js
  - We are going to use typescript and tailwind
- [ ] set up database
  - We are going to use Prisma and SQLLite
- [ ] create beats model
- [ ] create beat interface
  - [ ] interface to create  it
  - [ ]  interface  to read it
  - [ ] interface  to update it
  - [ ] interface to delete it

**Comment by victorkane** [comment]
- prototype
![kalliope-01-2023-10-11 11 04 58](https://github.com/kalliope-km/kalliope-prototype-01/assets/106342/b4c9844a-70f9-4cfb-b8ce-608b72c9557d)
- ideas for future
![kalliope-01-2023-10-11 11 15 54](https://github.com/kalliope-km/kalliope-prototype-01/assets/106342/84d6f10d-aec2-4f3c-be7e-26ff71fcde3c)

**Comment by victorkane** [comment]
Regarding PR #4

**Comment by victorkane** [comment]
- [ ] Take our Beat CRUD prototype and make a new dev instantiation on my computer
- [ ] Discover best practices with Prisma + SQLite for team dev process
- [ ] What do I do to get it running
- [ ] Document here that process, and make any changes I need to in the crud-beat branch

**Comment by victorkane** [comment]
Review server/client refresh on new beat creation

- make a cache (static forever)
- make it dynamic (from server) 
- minimum time for new revalidation
